spring.application.name=anivault

# PostgreSQL (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/anivault
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=anivault
spring.datasource.password=anivault

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

# CORS
spring.web.cors.allowed-origins=http://localhost:4200

# JWT
jwt.secret=anivault-super-secret-key-that-is-at-least-32-characters-long
jwt.expiration=86400000
